Update build.gradle
> Task :run FAILED
Error: Could not find or load main class ohtu.Main
Caused by: java.lang.ClassNotFoundException: ohtu.Main

Terminaalista gradle run komento ei toimi kun MainClass = 'ohtu.Main'